set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports converted]
set_property IOSTANDARD LVCMOS33 [get_ports data_valid]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports rx_busy]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports tx_busy]
set_property DRIVE 12 [get_ports converted]
set_property DRIVE 12 [get_ports data_valid]
set_property DRIVE 12 [get_ports rx_busy]
set_property DRIVE 12 [get_ports tx]
set_property DRIVE 12 [get_ports tx_busy]
set_property SLEW SLOW [get_ports converted]
set_property SLEW SLOW [get_ports data_valid]
set_property SLEW SLOW [get_ports rx_busy]
set_property SLEW SLOW [get_ports tx]
set_property SLEW SLOW [get_ports tx_busy]
set_property PACKAGE_PIN W5 [get_ports clk_100MHz]
set_property PACKAGE_PIN L1 [get_ports converted]
set_property PACKAGE_PIN P1 [get_ports data_valid]
set_property PACKAGE_PIN N3 [get_ports rx_busy]
set_property PACKAGE_PIN P3 [get_ports tx_busy]
set_property PACKAGE_PIN B18 [get_ports rx]
set_property PACKAGE_PIN A18 [get_ports tx]




